service: medium-latest-getter
provider:
  name: aws
  runtime: nodejs6.10

package:
  artifact: dst.zip

functions:
  getLatestPosts:
    handler: handler.getLatestPosts
    timeout: 10
    events:
      - http:
          path: getLatestPosts
          method: get

resources:
  Resources:
    GetLatestPostsLogGroup:
      Properties:
        RetentionInDays: "30"
